config/routes.rb
Property::Application.routes.draw do
  resources :tenants

  resources :buildings

  resources :landlords

end

app/models/building.rb
class Building < ActiveRecord::Base
  belongs_to :landlord
  has_many :tenants
  attr_accessible :name, :landlord_id
end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  attr_accessible :name
  has_many :tenants, :through => :buildings
  has_many :buildings
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  belongs_to :building
  attr_accessible :name, :building_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buildings }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    @building = Building.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/new
  # GET /buildings/new.json
  def new
    @building = Building.new
    @landlord = Landlord.all 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/1/edit
  def edit
    @building = Building.find(params[:id])
    @landlord = Landlord.all
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(params[:building])

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: "new" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.json
  def update
    @building = Building.find(params[:id])

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @landlords }
    end
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
    @landlord = Landlord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @landlord }
    end
  end

  # GET /landlords/new
  # GET /landlords/new.json
  def new
    @landlord = Landlord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @landlord }
    end
  end

  # GET /landlords/1/edit
  def edit
    @landlord = Landlord.find(params[:id])
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(params[:landlord])

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render json: @landlord, status: :created, location: @landlord }
      else
        format.html { render action: "new" }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /landlords/1
  # PUT /landlords/1.json
  def update
    @landlord = Landlord.find(params[:id])

    respond_to do |format|
      if @landlord.update_attributes(params[:landlord])
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord = Landlord.find(params[:id])
    @landlord.destroy

    respond_to do |format|
      format.html { redirect_to landlords_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  # GET /tenants
  # GET /tenants.json
  def index
    @tenants = Tenant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tenants }
    end
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
    @tenant = Tenant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tenant }
    end
  end

  # GET /tenants/new
  # GET /tenants/new.json
  def new
    @tenant = Tenant.new
    @building = Building.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tenant }
    end
  end

  # GET /tenants/1/edit
  def edit
    @tenant = Tenant.find(params[:id])
    @building = Building.all
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(params[:tenant])

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render json: @tenant, status: :created, location: @tenant }
      else
        format.html { render action: "new" }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tenants/1
  # PUT /tenants/1.json
  def update
    @tenant = Tenant.find(params[:id])

    respond_to do |format|
      if @tenant.update_attributes(params[:tenant])
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant = Tenant.find(params[:id])
    @tenant.destroy

    respond_to do |format|
      format.html { redirect_to tenants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :landlord %><br />
    <%= collection_select(:building, :landlord_id, @landlord, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing buildings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Landlord</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buildings.each do |building| %>
  <tr>
    <td><%= building.name %></td>
    <td><%= building.landlord %></td>
    <td><%= link_to 'Show', building %></td>
    <td><%= link_to 'Edit', edit_building_path(building) %></td>
    <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @building.name %>
</p>

<p>
  <b>Landlord:</b>
  <%= @building.landlord.name %>
</p>


<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>

app/views/landlords/_form.html.erb
<%= form_for(@landlord) do |f| %>
  <% if @landlord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landlord.errors.count, "error") %> prohibited this landlord from being saved:</h2>

      <ul>
      <% @landlord.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/landlords/edit.html.erb
<h1>Editing landlord</h1>

<%= render 'form' %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/landlords/index.html.erb
<h1>Listing landlords</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @landlords.each do |landlord| %>
  <tr>
    <td><%= landlord.name %></td>
    <td><%= link_to 'Show', landlord %></td>
    <td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
    <td><%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Landlord', new_landlord_path %>

app/views/landlords/new.html.erb
<h1>New landlord</h1>

<%= render 'form' %>

<%= link_to 'Back', landlords_path %>

app/views/landlords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @landlord.name %>
</p>

<% @landlord.tenants.each do |t| %>

<%= t.name %> </br>
<% end %>


<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Property</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tenants/_form.html.erb
<%= form_for(@tenant) do |f| %>
  <% if @tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
      <% @tenant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :building %><br />
    <%= collection_select(:tenant, :building_id, @building, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<h1>Listing tenants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Building</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tenants.each do |tenant| %>
  <tr>
    <td><%= tenant.name %></td>
    <td><%= tenant.building.name %></td>
    <td><%= link_to 'Show', tenant %></td>
    <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
    <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render 'form' %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tenant.name %>
</p>

<p>
  <b>Building:</b>
  <%= @tenant.building.name %>
</p>


<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>